name: CDKTF Build and Synthesize

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run synth
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
          STAGE: "ci-test"
          ROOT_DOMAIN: ${{ secrets.ROOT_DOMAIN }}
          S3_BACKEND_BUCKET: ${{ secrets.S3_BACKEND_BUCKET }}
          S3_BACKEND_LOCK_TABLE: ${{ secrets.S3_BACKEND_LOCK_TABLE }}
